version: 0.2

# ENV Vars to set in CodeBuild
#
# AWS_REGION      - AWS Default Region     (e.g. us-east-1)
# IMAGE_REPO_NAME - Name of the image repo (e.g. my-app)
# IMAGE_TAG       - Tag for the image      (e.g. latest)
# AWS_ACCOUNT_ID  - Remote AWS account id  (e.g. 555555555555)

phases:
    install:
        commands:
            - git log -1
            - printenv
            - whoami
            - echo $CODEBUILD_BUILD_ID
            - cd ./hello-service
    pre_build:
        commands:
            - echo "ECR login"
            - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
    build:
        commands:
            - echo "Building image"
            - sbt docker:publishLocal
    post_build:
        commands:
            - echo "Publishing to ECR"
            - sbt -Daws_repo=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ docker:publish
            # - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
