version: 0.2

# ENV Vars to set in CodeBuild
#
# AWS_REGION      - AWS Default Region     (e.g. us-east-1)
# IMAGE_REPO_NAME - Name of the image repo (e.g. my-app)
# IMAGE_TAG       - Tag for the image      (e.g. latest)
# AWS_ACCOUNT_ID  - Remote AWS account id  (e.g. 555555555555)

phases:
    install:
        commands:
            - echo "Installing Docker"
            - curl -fsSL get.docker.com | sh
            - git log -1
            - printenv
    build:
        commands:
            - cd ./hello-service
            - echo "Building image"
            - sbt -Dtests_only docker:stage
            - docker build -t hello-tests -f ./target/docker/stage/Dockerfile
            - docker run --rm hello-tests