version: 0.2

# ENV Vars to set in CodeBuild
#
# AWS_REGION      - AWS Default Region     (e.g. us-east-1)
# IMAGE_REPO_NAME - Name of the image repo (e.g. my-app)
# IMAGE_TAG       - Tag for the image      (e.g. latest)
# AWS_ACCOUNT_ID  - Remote AWS account id  (e.g. 555555555555)

phases:
    install:
        commands:
            - git log -1
            - printenv
    build:
        commands:
            - cd ./hello-service
            - sbt test